# syntax=docker/dockerfile:1.3-labs

FROM ubuntu:25.04

RUN <<EOF
    apt-get update
    apt-get install --no-install-recommends -y
                        sudo \
                        passwd \
                        clang \
                        build-essential \
                        ccache \
                        cmake \
                        autoconf \
                        automake \
    apt-get autoremove
    apt-get clean
    rm -rf /var/lib/apt/lists/*
EOF
