name: Documentation Build and Deploy

on:
  push:
    tags:
      - 'v*'  # 匹配 v 开头的标签，如 v1.0.0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz imagemagick make

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt

      - name: Build documentation
        run: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          commit_message: "docs: update documentation [skip ci]"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
