name: Ubuntu Package Test

on:
  push:
    paths:
      - 'source/env_dev/ubuntu/env_ubuntu.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_2004.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_2204.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_2404.conf'
      - '.github/workflows/ubuntu-package-test.yml'
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Test all Ubuntu versions'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'

jobs:
  test-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version: [20.04, 22.04, 24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test Docker image
        run: |
          cat > Dockerfile << EOF
          FROM ubuntu:${{ matrix.ubuntu-version }}
          RUN apt-get update && apt-get install -y apt-utils
          COPY source/env_dev/ubuntu/env_ubuntu.conf /tmp/common.conf
          COPY source/env_dev/ubuntu/env_ubuntu_${{ matrix.ubuntu-version }}.conf /tmp/version.conf
          RUN cat /tmp/common.conf /tmp/version.conf | grep -v '^#' | grep -v '^$' | xargs apt-get install -y
          EOF
          docker buildx build --load -t ubuntu-test:${{ matrix.ubuntu-version }} .
          docker run --rm ubuntu-test:${{ matrix.ubuntu-version }} bash -c "echo 'All packages installed successfully'"
