name: Ubuntu Package Test

on:
  push:
    paths:
      - 'source/env_dev/ubuntu/env_ubuntu.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_20.04.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_22.04.conf'
      - 'source/env_dev/ubuntu/env_ubuntu_24.04.conf'
      - '.github/workflows/ubuntu-package-test.yml'
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Test all Ubuntu versions'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'

jobs:
  test-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version: [20.04, 22.04, 24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test Docker image
        run: |
          # Generate Dockerfile using the script
          cd source/env_dev/ubuntu
          chmod +x generate_scripts.sh
          ./generate_scripts.sh

          # Build and test the image
          docker buildx build --load -f Dockerfile.ubuntu${{ matrix.ubuntu-version }} -t ubuntu-test:${{ matrix.ubuntu-version }} .
          docker run --rm ubuntu-test:${{ matrix.ubuntu-version }} bash -c "echo 'All packages installed successfully'"

          # Clean up generated files
          rm Dockerfile.ubuntu* install_packages_ubuntu*.sh
